permalink: pretty
markdown: redcarpet
pygments: true

exclude: ["CNAME", "README", "Gemfile", "Gemfile.lock", "Procfile", "config.rb", "sass"]

title: Gowalla Engineering
url: http://engineering.gowalla.com

team:
  -
    id: ak
    name: "Adam Keys"
    description: "API &amp; Platform Developer. Telling a joke and/or making Gowalla code."
    gowalla: therealadam
    github: therealadam
    twitter: therealadam

  -
    id: jc
    name: "John Critz"
    description: "Platform Developer. NERF and explosions expert."
    gowalla: jc
    github: critzjm
    twitter: critzjm

  -
    id: apd
    name: "Andrew Dupont"
    description: "Platform &amp; Web Developer. JavaScript sniper. Sugar-Free Red Bull addict."
    gowalla: savetheclocktower
    github: savetheclocktower
    twitter: andrewdupont

  -
    id: am
    name: "Adam McManus"
    description: "Operations Engineer. I like to ride my bike. Lots."
    gowalla: amcmanus
    github: amcmanus
    twitter: amcmanus

  -
    id: mt
    name: "Mattt Thompson"
    description: "iOS Developer. Hacker from the Rustbelt."
    gowalla: mattt
    github: mattt
    twitter: mattt

  -
    id: rs
    name: "Richard Schneeman"
    description: "Platform &amp; Web Developer. A location based ruby hacker."
    gowalla: schneems
    github: schneems
    twitter: schneems

  -
    id: kl
    name: "Kevin Lord"
    description: "iOS Developer, Operations Engineer. I like movies, watching sunsets, and long walks through code. Also, black shirts."
    gowalla: lordkev
    github: lordkev
    twitter: lordkev

  -
    id: sco
    name: "Scott Raymond"
    description: "Co-founder & CTO, iOS Developer. Ruby, Cocoa, & JavaScript developer. Author. Indoorsman."
    gowalla: sco
    github: sco
    twitter: sco

  -
    id: soop
    name: "Adam Michela"
    description: "Designer, Web Developer. I ride bicycles, and raise a couple of awesome kids. How about you?"
    gowalla: soopa
    github: soopa
    twitter: soopa

  -
    id: bf
    name: "Brad Fults"
    description: "Platform Developer. Background in JavaScript and front-end web development. Prefers simplicity, directness, red wine, fast cars and is healthily obsessed with quality."
    gowalla: h3h
    github: h3h
    twitter: h3h

  -
    id: pm
    name: "Philip McAllister"
    description: "Android Developer."
    gowalla: mcalliph
    github: mcalliph
    twitter: mcalliph

  -
    id: tp
    name: "Thorben Primke"
    description: "BlackBerry Developer."
    gowalla: tprimke
    github: thorbenprimke
    twitter: tprimke

  -
    id: dy
    name: "Drew Yeaton"
    description: "Designer &amp; Mobile Developer. I have 4 limbs dedicated to the eventual procreation of a progenitor species. I eat on a daily basis and play piano nightly."
    gowalla: xeeton
    github: drewyeaton
    twitter: xeeton

